name: CI

on: [push]

jobs:
  build-windows:
    name: Build-Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Generate
      run: cmake . -B_build
    - name: Compile
      run: cmake --build _build

  build-macOS:
    name: Build-macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Generate
      run: cmake . -B_build
    - name: Compile
      run: cmake --build _build

  build-ubuntu:
    name: Build-Ubuntu
    runs-on: ubuntu-latest
    env:
      CXX: /usr/bin/g++-8
      CC: /usr/bin/gcc-8

    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: sudo apt-get install xorg-dev libglu1-mesa-dev g++-8
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Generate
      run: cmake . -B_build
    - name: Compile
      run: cmake --build _build


